node ('master') {
    try {
        stage('Clone op-test') {
            git branch: 'kernel_install', url: 'https://github.com/sathnaga/op-test-framework.git'
            echo "Clone op-test"
            }
        stage('Install Upstream Kernel in Host') {
            echo "Install Upstream Kernel in Host"
            sh '''#!/bin/bash
            wget http://ltc-jenkins.aus.stglabs.ibm.com:81/sath/kvmci/machine_hostkernelinstall.conf -O machine_hostkernelinstall.conf
            ./op-test --run testcases.InstallUpstreamKernel.InstallUpstreamKernel -c ./machine_hostkernelinstall.conf'''
        }
        stage('Install Avocado') {
            echo "Install Avocado"
            sh '''#!/bin/bash
            wget http://ltc-jenkins.aus.stglabs.ibm.com:81/sath/kvmci/avocadoinstall.conf -O avocadoinstall.conf
            wget http://ltc-jenkins.aus.stglabs.ibm.com:81/sath/kvmci/machine_avocadoinstall.conf -O machine_avocadoinstall.conf
            ./op-test --run testcases.RunHostTest.RunHostTest -c ./machine_avocadoinstall.conf'''
        }
        stage('Build Upstream Guest Kernel') {
            echo "Build Upstream Guest Kernel"
            sh '''#!/bin/bash
            wget http://ltc-jenkins.aus.stglabs.ibm.com:81/sath/kvmci/guestkernelbuild.conf -O guestkernelbuild.conf
            wget http://ltc-jenkins.aus.stglabs.ibm.com:81/sath/kvmci/machine_guestkernelbuild.conf -O machine_guestkernelbuild.conf
            ./op-test --run testcases.RunHostTest.RunHostTest -c ./machine_guestkernelbuild.conf'''
        }
        stage('Build Upstream Qemu') {
            echo "Build Upstream Qemu"
            sh '''#!/bin/bash
            wget http://ltc-jenkins.aus.stglabs.ibm.com:81/sath/kvmci/qemubuild.conf -O qemubuild.conf
            wget http://ltc-jenkins.aus.stglabs.ibm.com:81/sath/kvmci/machine_qemubuild.conf -O machine_qemubuild.conf
            ./op-test --run testcases.RunHostTest.RunHostTest -c ./machine_qemubuild.conf'''
        }
        stage('Build Upstream Libvirt') {
            echo "Build Upstream Libvirt"
            sh '''#!/bin/bash
            wget http://ltc-jenkins.aus.stglabs.ibm.com:81/sath/kvmci/libvirtbuild.conf -O libvirtbuild.conf
            wget http://ltc-jenkins.aus.stglabs.ibm.com:81/sath/kvmci/machine_libvirtbuild.conf -O machine_libvirtbuild.conf
            ./op-test --run testcases.RunHostTest.RunHostTest -c ./machine_libvirtbuild.conf'''
        }
        stage('Run Avocado tests with Upstream Kernel, Qemu, Libvirt') {
            echo "Run Avocado tests with Upstream Kernel, Qemu, Libvirt"
            sh '''#!/bin/bash
            wget http://ltc-jenkins.aus.stglabs.ibm.com:81/sath/kvmci/avocadokvmtests.conf -O avocadokvmtests.conf
            wget http://ltc-jenkins.aus.stglabs.ibm.com:81/sath/kvmci/machine_avocadokvmtests.conf -O machine_avocadokvmtests.conf
            ./op-test --run testcases.RunHostTest.RunHostTest -c ./machine_avocadokvmtests.conf'''
        }
    } catch (e) {
        throw e
    }
    finally {
        stage('Pulish Results') {
            echo "Pulish Results"
            junit allowEmptyResults: true, testResults: 'test-reports/test-run*/TEST-*.xml,test-reports/test-run*/host-results/*/results.xml'
            archiveArtifacts allowEmptyArchive: true, artifacts: 'test-reports/**', fingerprint: true
            cleanWs()
            slackSend channel: '#ltc-test-kop', message: 'Completed ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>) '
        }
    }
}
